// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4T9naK3cFJJPluLtZQqiwzU4f6kuzGaY',
    appId: '1:691106091936:web:7ab171478e876b6488cac5',
    messagingSenderId: '691106091936',
    projectId: 'dtracker-db-lagria',
    authDomain: 'dtracker-db-lagria.firebaseapp.com',
    storageBucket: 'dtracker-db-lagria.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMQmHSA5AYxnCHBaN3_t3X0y_wXMbPRA',
    appId: '1:691106091936:android:542205f10413d2af88cac5',
    messagingSenderId: '691106091936',
    projectId: 'dtracker-db-lagria',
    storageBucket: 'dtracker-db-lagria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOjhfZgvz-C553VcOaIAwtlEp6TUoLp0',
    appId: '1:691106091936:ios:fe5ca2674e212e5f88cac5',
    messagingSenderId: '691106091936',
    projectId: 'dtracker-db-lagria',
    storageBucket: 'dtracker-db-lagria.appspot.com',
    iosClientId: '691106091936-3849os4v3g4in726ptq2n0qjo6ql1kp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtracketProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDOjhfZgvz-C553VcOaIAwtlEp6TUoLp0',
    appId: '1:691106091936:ios:fe5ca2674e212e5f88cac5',
    messagingSenderId: '691106091936',
    projectId: 'dtracker-db-lagria',
    storageBucket: 'dtracker-db-lagria.appspot.com',
    iosClientId: '691106091936-3849os4v3g4in726ptq2n0qjo6ql1kp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtracketProject',
  );
}
